version: '2'
services:
  app:
    image: rachelpeters/hacktt-backend
    ports:
      - "80:2375"
    environment:
      DB_USER: admin
      DB_NAME: user
      DB_PASSWORD: password123
      DB_HOST: ed1266uth4bae8k.cmdzaigiudxs.us-east-1.rds.amazonaws.com
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
      SECRET_KEY_BASE: 5156ca5a10c6842c4359d9a78ba14a4ba91cee9394d2e87bb783a0f770469d6afd725d40346d328b705cb2b74ef7de2005701c3449a1dbd1d1bc163ce3b67ec1
